using EasyEnglish.Core.Entities;
using EasyEnglish.Core.Interfaces.Fields;
using MukhaLab.Database;
using System.Text.Json.Serialization;

namespace EasyEnglish.Core.Models;

public class UnitModel : AbstractModel, IReviewInfo, IAuditInfo, IGuidRecord
{
    public Guid RecordGuid { get; set; } = Guid.NewGuid();

    public string Title { get; set; } = "Autogenerated";

    public string? Description { get; set; }

    public string? Content { get; set; }

    public string? LanguageCode { get; set; }

    public DateTime? LastReviewDate { get; set; }

    public int ReviewCount { get; set; } = 0;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime? UpdatedAt { get; set; }

    public int CourseId { get; set; }

    public IList<WordModel>? Words { get; set; }

    public IList<IrregularFormModel>? IrregularForms { get; set; }

    [JsonIgnore]
    public CourseModel? Course { get; set; }

    public UnitModel ClearKeyFields()
    {
        this.Id = 0;
        this.CourseId = 0;
        this.CreatedAt = DateTime.UtcNow;
        this.UpdatedAt = null;

        if (this.Words is not null)
        {
            foreach (var word in this.Words)
            {
                word.Id = 0;
                //word.Pronunciation = null;
                //word.LastTotalAttempts = 0;
                //word.LastIncorrectAttempts = 0;
                word.UnitId = 0;
                word.CreatedAt = DateTime.UtcNow;
                word.UpdatedAt = null;
            }
        }

        return this;
    }

    public UnitModel ClearLearningProgress()
    {
        this.LastReviewDate = null;
        this.ReviewCount = 0;

        if (this.Words is not null)
        {
            foreach (var word in this.Words)
            {
                word.Rate = 3.0f;
                word.LastReviewDate = null;
                word.ReviewCount = 0;
            }
        }

        return this;
    }

    public UnitModel RemoveExamples()
    {
        if (this.Words is not null)
        {
            foreach (var word in this.Words)
            {

                word.Examples = [];
            }
        }

        return this;
    }
}
