// <auto-generated />
using System;
using EasyEnglish.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyEnglish.Data.Migrations
{
    [DbContext(typeof(EasyEnglishDbContext))]
    [Migration("20260710051339_AddRecordGuidToChildEntities")]
    partial class AddRecordGuidToChildEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("EasyEnglish.Core.Entities.CourseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("language_code");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.ExampleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("sentence");

                    b.Property<string>("Translation")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("translation");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("word_id");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("examples");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.IrregularFormEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstForm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_form");

                    b.Property<byte[]>("FirstFormPronunciation")
                        .HasColumnType("BLOB")
                        .HasColumnName("first_form_pronunciation");

                    b.Property<string>("FirstFormTranscription")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_form_transcription");

                    b.Property<string>("FirstFormTranslation")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_form_translation");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_review_date");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("part_of_speech");

                    b.Property<float>("Rate")
                        .HasColumnType("REAL")
                        .HasColumnName("rate");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("review_count");

                    b.Property<string>("SecondForm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("second_form");

                    b.Property<byte[]>("SecondFormPronunciation")
                        .HasColumnType("BLOB")
                        .HasColumnName("second_form_pronunciation");

                    b.Property<string>("SecondFormTranscription")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("second_form_transcription");

                    b.Property<string>("SecondFormTranslation")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("second_form_translation");

                    b.Property<string>("ThirdForm")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("third_form");

                    b.Property<byte[]>("ThirdFormPronunciation")
                        .HasColumnType("BLOB")
                        .HasColumnName("third_form_pronunciation");

                    b.Property<string>("ThirdFormTranscription")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("third_form_transcription");

                    b.Property<string>("ThirdFormTranslation")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("third_form_translation");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("irregular_forms");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.StudyCardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("CodeBlock")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("code_block");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Dialogue")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("dialogue");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_review_date");

                    b.Property<float>("Rate")
                        .HasColumnType("REAL")
                        .HasColumnName("rate");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<int?>("RevealMode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reveal_mode");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("review_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("study_cards");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.TestCardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CorrectAnswers")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("correct_answers");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("explanation");

                    b.Property<string>("FormattedText")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("formatted_text");

                    b.Property<string>("Hint")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("hint");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB")
                        .HasColumnName("image");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_review_date");

                    b.Property<string>("Options")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("options");

                    b.Property<string>("Question")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<float>("Rate")
                        .HasColumnType("REAL")
                        .HasColumnName("rate");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("review_count");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("test_cards");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.UnitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_review_date");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("review_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("units");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.WordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_review_date");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<byte[]>("Pronunciation")
                        .HasColumnType("BLOB")
                        .HasColumnName("pronunciation");

                    b.Property<float>("Rate")
                        .HasColumnType("REAL")
                        .HasColumnName("rate");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("review_count");

                    b.Property<string>("Transcription")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("transcription");

                    b.Property<string>("Translation")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("translation");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("words");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.ExampleEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.WordEntity", "Word")
                        .WithMany("Examples")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.IrregularFormEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.UnitEntity", "Unit")
                        .WithMany("IrregularForms")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.StudyCardEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.UnitEntity", "Unit")
                        .WithMany("StudyCards")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.TestCardEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.UnitEntity", "Unit")
                        .WithMany("TestCards")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.UnitEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.CourseEntity", "Course")
                        .WithMany("Units")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.WordEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.UnitEntity", "Unit")
                        .WithMany("Words")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.CourseEntity", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.UnitEntity", b =>
                {
                    b.Navigation("IrregularForms");

                    b.Navigation("StudyCards");

                    b.Navigation("TestCards");

                    b.Navigation("Words");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.WordEntity", b =>
                {
                    b.Navigation("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
