// <auto-generated />
using System;
using EasyEnglish.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyEnglish.Data.Migrations
{
    [DbContext(typeof(EasyEnglishDbContext))]
    [Migration("20260111164259_UpdateUnitsAndWordsTables")]
    partial class UpdateUnitsAndWordsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("EasyEnglish.Core.Entities.CourseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.ExampleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("sentence");

                    b.Property<string>("Translation")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("translation");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("word_id");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("examples");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.GrammarTestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_review_date");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("review_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("grammar_tests");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.GrammarTopicEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_review_date");

                    b.Property<int?>("ParentTopicId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_topic_id");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("review_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentTopicId");

                    b.ToTable("grammar_topics");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.GrammarTopicTestEntity", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("topic_id");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("test_id");

                    b.HasKey("TopicId", "TestId");

                    b.HasIndex("TestId");

                    b.ToTable("grammar_topic_tests");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.IrregularFormEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte[]>("Pronunciation")
                        .HasColumnType("BLOB")
                        .HasColumnName("pronunciation");

                    b.Property<string>("Transcription")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("transcription");

                    b.Property<string>("Translation")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("translation");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.ToTable("irregular_forms");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.IrregularWordFormsEntity", b =>
                {
                    b.Property<int>("FirstFormId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("first_form_id");

                    b.Property<int>("SecondFormId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("second_form_id");

                    b.Property<int>("ThirdFormId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("third_form_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_review_date");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("review_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("FirstFormId", "SecondFormId", "ThirdFormId");

                    b.HasIndex("SecondFormId");

                    b.HasIndex("ThirdFormId");

                    b.ToTable("irregular_word_forms");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.StudyCardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Dialogue")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("dialogue");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_review_date");

                    b.Property<float>("Rate")
                        .HasColumnType("REAL")
                        .HasColumnName("rate");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("review_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("study_cards");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.StudyCardItemEntity", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("card_id");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("word_id");

                    b.HasKey("CardId", "WordId");

                    b.HasIndex("WordId");

                    b.ToTable("study_card_items");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.TestCardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CorrectAnswers")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("correct_answers");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_review_date");

                    b.Property<string>("Mask")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("mask");

                    b.Property<string>("Options")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("options");

                    b.Property<float>("Rate")
                        .HasColumnType("REAL")
                        .HasColumnName("rate");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("review_count");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("test_id");

                    b.Property<string>("TestType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("test_type");

                    b.Property<string>("Text")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("test_cards");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.UnitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_review_date");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("level");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("review_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("units");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.WordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Definition")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("definition");

                    b.Property<string>("Explanation")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("explanation");

                    b.Property<int?>("IrregularFormsFirstFormId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IrregularFormsSecondFormId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IrregularFormsThirdFormId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_review_date");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("level");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("part_of_speech");

                    b.Property<byte[]>("Pronunciation")
                        .HasColumnType("BLOB")
                        .HasColumnName("pronunciation");

                    b.Property<float>("Rate")
                        .HasColumnType("REAL")
                        .HasColumnName("rate");

                    b.Property<Guid>("RecordGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("guid");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("review_count");

                    b.Property<string>("Transcription")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("transcription");

                    b.Property<string>("Translation")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("translation");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("IrregularFormsFirstFormId", "IrregularFormsSecondFormId", "IrregularFormsThirdFormId");

                    b.ToTable("words");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.WordTagEntity", b =>
                {
                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("word_id");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tag_id");

                    b.HasKey("WordId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("word_tags");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.ExampleEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.WordEntity", "Word")
                        .WithMany("Examples")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.GrammarTopicEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.GrammarTopicEntity", "ParentTopic")
                        .WithMany("ChildTopics")
                        .HasForeignKey("ParentTopicId");

                    b.Navigation("ParentTopic");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.GrammarTopicTestEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.GrammarTestEntity", "GrammarTest")
                        .WithMany("GrammarTopicTests")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyEnglish.Core.Entities.GrammarTopicEntity", "GrammarTopic")
                        .WithMany("GrammarTopicTests")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrammarTest");

                    b.Navigation("GrammarTopic");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.IrregularWordFormsEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.WordEntity", "FirstForm")
                        .WithMany()
                        .HasForeignKey("FirstFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyEnglish.Core.Entities.IrregularFormEntity", "SecondForm")
                        .WithMany()
                        .HasForeignKey("SecondFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyEnglish.Core.Entities.IrregularFormEntity", "ThirdForm")
                        .WithMany()
                        .HasForeignKey("ThirdFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstForm");

                    b.Navigation("SecondForm");

                    b.Navigation("ThirdForm");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.StudyCardItemEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.StudyCardEntity", "StudyCard")
                        .WithMany("StudyCardItems")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyEnglish.Core.Entities.WordEntity", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyCard");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.TestCardEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.GrammarTestEntity", "GrammarTest")
                        .WithMany("TestCards")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrammarTest");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.UnitEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.CourseEntity", "Course")
                        .WithMany("Units")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.WordEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.UnitEntity", "Unit")
                        .WithMany("Words")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyEnglish.Core.Entities.IrregularWordFormsEntity", "IrregularForms")
                        .WithMany()
                        .HasForeignKey("IrregularFormsFirstFormId", "IrregularFormsSecondFormId", "IrregularFormsThirdFormId");

                    b.Navigation("IrregularForms");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.WordTagEntity", b =>
                {
                    b.HasOne("EasyEnglish.Core.Entities.TagEntity", "Tag")
                        .WithMany("WordTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyEnglish.Core.Entities.WordEntity", "Word")
                        .WithMany("WordTags")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.CourseEntity", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.GrammarTestEntity", b =>
                {
                    b.Navigation("GrammarTopicTests");

                    b.Navigation("TestCards");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.GrammarTopicEntity", b =>
                {
                    b.Navigation("ChildTopics");

                    b.Navigation("GrammarTopicTests");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.StudyCardEntity", b =>
                {
                    b.Navigation("StudyCardItems");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.TagEntity", b =>
                {
                    b.Navigation("WordTags");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.UnitEntity", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("EasyEnglish.Core.Entities.WordEntity", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("WordTags");
                });
#pragma warning restore 612, 618
        }
    }
}
